objects/Account.object
<CustomObject>
    <fields>
        <fullName>Original_Account_Id__c</fullName>
        <description>This is a placeholder to store the original account record&apos;s Id</description>
        <label>Original Account Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Registration_Number__c</fullName>
        <externalId>true</externalId>
        <label>Renewal Registration Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>RSA</fullName>
        <active>true</active>
        <label>RSA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regulatory_Transaction_Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulatory Transaction Fee</label>
        <referenceTo>RegulatoryTrxnFee</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmation_Number__c</fullName>
        <label>Confirmation Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReceiveDate__c</fullName>
        <label>ReceiveDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Regulatory_Transaction_Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulatory Transaction Fee</label>
        <referenceTo>RegulatoryTrxnFee</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponseData__c</fullName>
        <label>ResponseData</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Settlement_Submission_Date__c</fullName>
        <label>Settlement Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Paid_Amount__c</fullName>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ePay_Result_Message__c</fullName>
        <label>ePay Result Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ePay_Return_Code__c</fullName>
        <label>ePay Return Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Response</label>
    <nameField>
        <displayFormat>PGR-{000000}</displayFormat>
        <label>Response #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RegulatoryTrxnFee.object
<CustomObject>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due</fullName>
                    <default>true</default>
                    <label>Due</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PaymentResponseHandlerTest.cls
@isTest
public class PaymentResponseHandlerTest {
    
    @isTest
    Public static void test_Method2(){
        Test.startTest();
        ID accid;
        List<Payment_Response__c> PaymentResponselist = New List<Payment_Response__c>();
        List<Payment_Response__c> PaymentResponselist1 = New List<Payment_Response__c>();
        
        Account accRec = TestDataFactory_community.createAccountTestRec('TestAcc', 'RSA');
        insert accRec;
        
        Contact conrec = TestDataFactory_Community.createContactTestRec('bscjhb', 'john', 'abc@xyz.com', accRec.Id);
        insert conrec;
        
        Id RenewalRecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Renewal').getRecordTypeId();
        Account RenewalAcc = new Account();
        RenewalAcc.Name = 'RenAcc';
        RenewalAcc.Renewal_Registration_Number__c = '123445';
        RenewalAcc.Original_Account_Id__c=accRec.Id;
        RenewalAcc.RecordTypeId = RenewalRecordTypeID;
        Insert RenewalAcc;
        
        User testUser = TestDataFactory_Community.createTestUserRec('CDFA Agent Community Login User', 'test@user.com', conRec.Id);
        Insert testUser;
        
        system.runAs(testUser){
            RegulatoryAuthorizationType rAuth = TestDataFactory_Community.getRegAuthType();
            insert rAuth;
            
            BusinessLicense bl = TestDataFactory_Community.getBusnLicTestRec(accRec.Id, conrec.Id, rAuth.Id);
            insert bl;
            
            RegulatoryTrxnFee RTF = New RegulatoryTrxnFee();
            rtf.Comments = 'Comments';
            RTF.AccountId = accRec.id;
            rtf.Payment_Status__c = 'Paid';
            rtf.ParentRecordId = bl.id;
            rtf.Status = 'PAID';
            insert rtf;
            
            Payment_Request__c Pr = New Payment_Request__c();
            Pr.Account__c = accRec.id;
            pr.Status__c = 'Completed';
            pr.Regulatory_Transaction_Fee__c = rtf.Id;
            insert Pr;
            
            For (Payment_Request__c PayReq : [Select Id, Status__c, Account__c from Payment_Request__c Where Id=:Pr.id]){
                accid = PayReq.Account__c;
            }
            
            Payment_Response__c  paymentResponse = new Payment_Response__c();
            paymentResponse.ReceiveDate__c = System.today();
            paymentResponse.Account__c =accid;
            paymentResponse.ResponseData__c = 'paymentResponse';
            paymentResponse.ePay_Return_Code__c = 'Valic Code';
            paymentResponse.Total_Paid_Amount__c = 600;
            paymentResponse.Card_Type__c = 'Visa';
            paymentResponse.Payment_Request__c = pr.Id;
            paymentResponse.Status__c = 'Success';
            paymentResponse.ePay_Result_Message__c = 'Success';
            paymentResponse.Confirmation_Number__c = 200;
            paymentResponse.Settlement_Submission_Date__c = System.today();
            PaymentResponselist.add(paymentResponse);
            insert PaymentResponselist;
        }
        Test.stopTest();
    }
}