objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_Renewal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency Renewal</label>
        <referenceTo>Agency_Renewal__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Number__c</fullName>
        <externalId>true</externalId>
        <label>Registration Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>RSA</fullName>
        <active>true</active>
        <label>RSA</label>
    </recordTypes>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Agency_Renewal__c.object
<CustomObject>
    <fields>
        <fullName>Business_certified_standards_Third_Party__c</fullName>
        <defaultValue>false</defaultValue>
        <label>C3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_owns_the_standards_Agency__c</fullName>
        <defaultValue>false</defaultValue>
        <label>C1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_uses_certified_standards_owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>C2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Agency_Renewals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Payment Pending</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agency Declaration</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Agency Declaration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Declarations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorization_Code__c</fullName>
        <label>Authorization Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Paid_Amount__c</fullName>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Response</label>
    <nameField>
        <displayFormat>PGR-{000000}</displayFormat>
        <label>Response #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FormESectionController_test.cls
@isTest
public class FormESectionController_test {
    @isTest
    Private static void test_Method(){
        
        Try{
            Account accRec = TestDataFactory_Community.createAccountTestRec('TestAcc', 'RSA');
            Insert accRec;
            Contact conRec = TestDataFactory_Community.createContactTestRec('test','con','test@com.com',accRec.Id);
            Insert conRec;
            User testUser = TestDataFactory_Community.createTestUserRec('CDFA Agent Community Login User', 'test@user.com', conRec.Id);
            Insert testUser;
            List<Contact> testConList = TestDataFactory_Community.createContactsTestRec(accRec.Id, 5);
            insert testConList;
            Id accountRecordTypeId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Renewal').getRecordTypeId();
            Account renewalAcc = new Account(Name = 'TestAcc', Registration_Number__c='123', RecordTypeId = accountRecordTypeId);
            Insert renewalAcc;
            Agency_Renewal__c ar = new Agency_Renewal__c(Renewal_Account__c=renewalAcc.Id, Status__c='Payment Pending');
            insert ar;
            
            List<String> myl = new List<String>();
            myl.add('mark z');
            myl.add('My business owns the standards used by my Agency/Agents');
            myl.add('My business uses certified standards owned by county weights');
            myl.add('My business uses certified standards owned by a third-party');
          
            List<Id> PaymentRequestId = New List<Id>();
            List<Payment_Response__c> PaymentResponselist = New List<Payment_Response__c>();
            Payment_Request__c Pr = New Payment_Request__c();
            Pr.Account__c = accRec.id;
            pr.Status__c = 'Completed';
            insert Pr;
        
         PaymentRequestId.add(Pr.id);
            
            Payment_Response__c Prs = New Payment_Response__c();
            Prs.Account__c =accRec.id ;
            Prs.Unique_ID__c = Pr.id;
            Prs.Authorization_Code__c = 'Code';
            Prs.Card_Type__c = 'MC';        
            Prs.Total_Paid_Amount__c = 1500;
            PaymentResponselist.add(Prs);
            insert PaymentResponselist;
            
           /* system.runAs(testUser){
                // getSelectedValues
                FormESectionController.getSelectedValues(myl, accRec.Id);
                
                // updateAgencyApproval
                FormESectionController.updateAgencyApproval(myl, accRec.Id, 'sd');//SIGNTURE                
                List<Agency_Renewal__c> arl = [select id FROM Agency_Renewal__c Where Account__c =: accRec.Id];
                system.debug('size-- '+arl.size());
            } */
            
            List<Agency_Renewal__c> arList = new List<Agency_Renewal__c>();
            for(integer i=0; i<5; i++){
                Agency_Renewal__c agency1 = new Agency_Renewal__c();
                agency1.Business_certified_standards_Third_Party__c =false;
                agency1.Business_owns_the_standards_Agency__c = false;
                agency1.Business_uses_certified_standards_owned__c = false;
                agency1.Renewal_Account__c =renewalAcc.Id;
                agency1.Created_Date__c=DateTime.now();
                agency1.Status__c = 'In Progress';
                arList.add(agency1);
            }
            insert arList;
            
            system.runAs(testUser){
                Test.startTest();
                // getSelectedValues
               // FormESectionController.getSelectedValues_NOTUSED(myl, accRec.Id);
                
                
                // updateAgencyApproval
               FormESectionController.updateAgencyApproval(myl, accRec.Id, renewalAcc.Id, 'sd');//SIGNTURE
                FormESectionController.updateAgencyApproval(myl, accRec.Id, renewalAcc.Id, 'SIGNTURE');//SIGNTURE
                //call getAgencyRenewal
               FormESectionController.getAgencyRenewal(accRec.Id, renewalAcc.Id);
              
                
                // updateStatusPaid
              FormESectionController.updateStatusPaid(accRec.Id, Pr.id);
                
               // FormESectionController.updateAgencyApproval(myl, accRec.Id, 'SIGNTURE');
                
            }
            Test.stopTest();
            
        }catch(Exception e){
            system.debug(e.getLineNumber());
            system.debug(e.getMessage());
            system.debug(e.getTypeName());
        }
        
    }
}