objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regulatory_Transaction_Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulatory Transaction Fee</label>
        <referenceTo>RegulatoryTrxnFee</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RegulatoryTrxnFee.object
<CustomObject>
    <fields>
        <fullName>Due_Amount__c</fullName>
        <label>Due Amount</label>
        <summarizedField>RegulatoryTrxnFeeItem.FeeAmount</summarizedField>
        <summaryFilterItems>
            <field>RegulatoryTrxnFeeItem.Status__c</field>
            <operation>equals</operation>
            <value>Due, Pending</value>
        </summaryFilterItems>
        <summaryForeignKey>RegulatoryTrxnFeeItem.RegulatoryTrxnFeeId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Paid_Amount__c</fullName>
        <label>Paid Amount</label>
        <summarizedField>RegulatoryTrxnFeeItem.FeeAmount</summarizedField>
        <summaryFilterItems>
            <field>RegulatoryTrxnFeeItem.Status__c</field>
            <operation>equals</operation>
            <value>Paid</value>
        </summaryFilterItems>
        <summaryForeignKey>RegulatoryTrxnFeeItem.RegulatoryTrxnFeeId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due</fullName>
                    <default>true</default>
                    <label>Due</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RegulatoryTrxnFeeItem.object
<CustomObject>
    <fields>
        <fullName>Payment_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Regulatory Transaction Fee Items</relationshipLabel>
        <relationshipName>Regulatory_Transaction_Fee_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Due</fullName>
                    <default>true</default>
                    <label>Due</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSelected</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PaymentGatewayUtility.cls
public without sharing class PaymentGatewayUtility {

    public static User getUserInfo(String uId){
  		system.debug('uID =>'+uId);
        User lgdUser = [select Id,FirstName,LastName,Name,ContactId,Contact.AccountID from user where id=: uId];
        return lgdUser;
    }
    
    
    
    public static String getSiteURL(String siteNm){
        //CDFA Registered Service Agency
        Site site = [SELECT Id FROM Site WHERE UrlPathPrefix =:siteNm LIMIT 1];
        String communityUrl = [SELECT SecureURL FROM SiteDetail WHERE DurableId =: site.Id].SecureUrl;
        System.debug('Community url: ' + communityUrl);
        return communityUrl;
    }
    
    public static String getSfdcURL(){
        return URL.getSalesforceBaseUrl().toExternalForm();
    }
    
    
    // This method is being used in AccountLwcController apex class & retun List<RegulatoryTrxnFeeItem> to AccountLwcController controller class
    public Static List<RegulatoryTrxnFeeItem> getFeeItems(set<Id> itmId_st){
       List<RegulatoryTrxnFeeItem> itms_lst = [Select Id,Name,RegulatoryTrxnFeeId,FeeAmount,Status__c,isSelected__c from RegulatoryTrxnFeeItem where id in: itmId_st];
        return itms_lst;
    }
    
    
    // This method is being used in AccountLwcController apex class & return all the Fee & Fee items based on Account ID
    public static  List<RegulatoryTrxnFee> getFeeAndItemsFromAccount(String actId){
        List<RegulatoryTrxnFee> fee_Itms_ls = [Select Id,Name,AccountId,Status,TotalFeeAmount,Due_Amount__c,Paid_Amount__c,
                                               (Select Id,Name,RegulatoryTrxnFeeId,FeeAmount,Status__c from RegulatoryTrxnFeeItems 
                                               where Status__c='Due' or Status__c = 'Pending') 
                                               from RegulatoryTrxnFee where AccountId =:actId AND 
                                               ( Status =  'Due' OR Status = 'Partially Paid') limit 1];
        return fee_Itms_ls;
    }
    
    
    // This method is being used in PaymentReturn_Cntrlr apex class & return the TransactionFee record based on fee id
    public static RegulatoryTrxnFee getTransactionFeeRec(String feeId){
        RegulatoryTrxnFee fee_rec =  [Select Id,Name,AccountId,Status,Payment_Status__c,TotalFeeAmount,Due_Amount__c,Paid_Amount__c from RegulatoryTrxnFee where id =:feeId];
        return fee_rec;
    }
    
    // This method is being used in PaymentReturn_Cntrlr apex class & return the list of PaymentRequest records
    public static  List<Payment_Request__c> getPaymentRequestRec(String paymentReqId){
        List<Payment_Request__c> req_rec_ls = [select Id,name,Status__c,Account__c,Regulatory_Transaction_Fee__c  from Payment_Request__c where id =: paymentReqId ];
        return req_rec_ls;
    }    
        
    // This method is being used in PaymentReturn_Cntrlr apex class  & return all the Fee & Fee items based on Fee ID
    public static  List<RegulatoryTrxnFee> getFeeAndItemsFromFee(String feeId){
        List<RegulatoryTrxnFee> fee_Itms_ls = [Select Id,Name,AccountId,Status,TotalFeeAmount,(Select Id,Name,RegulatoryTrxnFeeId,FeeAmount,Status__c,isSelected__c from RegulatoryTrxnFeeItems where Status__c = 'Pending' OR Status__c = 'Due' ) from RegulatoryTrxnFee where id=: feeId];
        return fee_Itms_ls;
    }
    
}