objects/Account.object
<CustomObject>
    <fields>
        <fullName>Registration_Type__c</fullName>
        <description>Agency registration type.</description>
        <label>Registration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Process__c</fullName>
        <label>Renewal Process</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>RSA</fullName>
        <active>true</active>
        <label>RSA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AssociatedLocation.object
<CustomObject>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>locationFromAppRecordTypeCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to check whether location created from Application Account Record Type.</description>
        <label>locationFromAppRecordTypeCreated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/RegulatoryTrxnFee.object
<CustomObject>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due</fullName>
                    <default>true</default>
                    <label>Due</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Account_Id__c</fullName>
        <label>Renewal Account Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/RegulatoryTrxnFeeItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Due</fullName>
                    <default>true</default>
                    <label>Due</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>referenceId__c</fullName>
        <label>referenceId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RSAAlTriggerHandler.cls
public without sharing class RSAAlTriggerHandler {
    
    public static void beforeInsertRSAAl(List<AssociatedLocation>asoLocNewList){

    }
    public static void beforeDeleteRSAAl(List<AssociatedLocation>asoLocOldList,Map<Id,AssociatedLocation>asoLocOldMap){
        
    }
    public static void afterInsertRSAAl(List<AssociatedLocation>asoLocNewList,Map<Id,AssociatedLocation>asoLocNewMap){
        Try{
            
            String AccRecordType;
            String Original_Account_Id;
            String Altype;
            String recType;
            String RenewalStatus;
            ID  locId;
			AssociatedLocation alRecord= new AssociatedLocation();
            
                
            Set<Id>ParentRecordIdSet = New Set<Id>();
            Set<Id>locationIdSet = New Set<Id>();
            for(AssociatedLocation alRec:asoLocNewList){
                ParentRecordIdSet.add(alRec.ParentRecordId);
                locationIdSet.add(alRec.locationid);
                alRecord = alRec;
            }
            
            
            List<Account>accList = [select recordtype.Name, Renewal_Process__c,Registration_Type__c FROM Account where id IN: ParentRecordIdSet limit 1];
            if(!accList.isEmpty()){
                recType = accList[0].recordtype.Name;
                RenewalStatus = accList[0].Renewal_Process__c;
                system.debug('recType=>'+recType+'==RenewalStatus=>'+RenewalStatus);
            }
            
            if(recType == 'RSA' && (RenewalStatus == 'Completed' || RenewalStatus == null)&& accList[0].Registration_Type__c!='New' && alRecord.locationFromAppRecordTypeCreated__c==False){
                system.debug('Inside RSA Account in trigger==>'+ParentRecordIdSet+'  recType==>'+recType);
                //BusinessLicense bl = [select id from BusinessLicense where accountid IN:ParentRecordIdSet and status = 'Active'];                    
                BusinessLicense bl = [select id from BusinessLicense where accountid IN:ParentRecordIdSet order by periodEnd desc LIMIT 1];
                list<RegulatoryTrxnFee> lstRtf = [select id from RegulatoryTrxnFee where accountid IN:ParentRecordIdSet and (status = 'Due' or status = 'Partially Paid') LIMIT 1];
                 
                // Rxn Fee Part
                string ParentRecordIdValue = null;
                for (string setElement : ParentRecordIdSet) {
                    ParentRecordIdValue = setElement;
                    break;
                }
                
                id rtfid;
                if (lstRtf.size() == 0) {
                    RegulatoryTrxnFee newRtf = new RegulatoryTrxnFee();
                    newRtf.accountid = ParentRecordIdValue;
                    newRtf.ParentRecordId = bl.id;
                    newRtf.payment_status__c = 'Due';
                    newRtf.DueDate = system.now();
                    newRtf.DueDate = newRtf.DueDate.addDays(60);
                    newRtf.status = 'Due';
                    //newRtf.Renewal_Account_Id__c= ;
                    insert newRtf;
                    rtfid = newRtf.id;
                } else {
                    rtfid = lstRtf[0].id;
                } // Txn Fee End
                
                // TXN fee Item start
                RegulatoryTrxnFeeItem newRtfi = new RegulatoryTrxnFeeItem();
                newRtfi.RegulatoryTrxnFeeId = rtfid;
                Schema.Location locname = [select name from location where id IN: locationIdSet limit 1];
                newRtfi.name = 'New Location - ' + locname.name;
                newRtfi.FeeAmount = 100;  
                newrtfi.referenceId__c = alRecord.Id; // to add AL Id 
                newRtfi.status__c = 'Due';
                insert newRtfi;
                // TXN fee Item End   
                
            }
        }Catch(Exception e){
            system.debug('Type-->> '+ e.getTypeName());
            system.debug('Line Number-->> '+e.getLineNumber());
            system.debug('Cause-->> '+e.getCause());
            system.debug('Message-->> '+e.getMessage());
        }
    }
    public static void afterUpdateRSAAl(List<AssociatedLocation>asoLocNewList,Map<Id,AssociatedLocation>asoLocNewMap,List<AssociatedLocation>asoLocOldList,Map<Id,AssociatedLocation>asoLocOldMap){
        
    }
    public static void afterDeleteRSAAl(List<AssociatedLocation>asoLocOldList,Map<Id,AssociatedLocation>asoLocOldMap){
        
    }
}