objects/Account_Associated_Location__c.object
<CustomObject>
    <fields>
        <fullName>ActiveTo__c</fullName>
        <label>ActiveTo</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active_From__c</fullName>
        <label>Active From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Associated_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Location</label>
        <referenceTo>AssociatedLocation</referenceTo>
        <relationshipLabel>Account Associated Locations</relationshipLabel>
        <relationshipName>Account_Associated_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LocationId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location Name</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Account Associated Locations</relationshipLabel>
        <relationshipName>Account_Associated_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentRecordId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Associated Locations</relationshipLabel>
        <relationshipName>Account_Associated_Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Associated Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Associated Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AssociatedLocation.object
<CustomObject>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountAssociatedLocHandler.cls
public without sharing class AccountAssociatedLocHandler {
    Public static void OnCreateAccAssociatedLoc(List<AssociatedLocation> newList ){
        List<Account_Associated_Location__c> associatedloc = new List<Account_Associated_Location__c>();
        for(AssociatedLocation asloc : newList){
            Account_Associated_Location__c accloc = new Account_Associated_Location__c();
            accloc.ActiveTo__c = asloc.ActiveTo;
            accloc.Active_From__c = asloc.ActiveFrom;
            accloc.ParentRecordId__c = asloc.ParentRecordId;
            accloc.Payment_Status__c = asloc.Payment_Status__c;
            accloc.Status__c = asloc.Status__c;
            accloc.Type__c =asloc.Type;
            accloc.LocationId__c = asloc.LocationId;
            accloc.Associated_Location__c =asloc.Id;
            accloc.Name = asloc.AssociatedLocationNumber;
            associatedloc.add(accloc);
            
        }
        insert associatedloc;
    }//end of OnCreateAccAssociatedLoc method
    
    Public static void onUpdateAccAssociatedLoc(List<AssociatedLocation> newlist){
        List<Account_Associated_Location__c> associatedlocToUpdate = new List<Account_Associated_Location__c>();
        system.debug(newlist.size()+ ' newlist Size '+newlist);
      
        if(newList.size()>0){
            for(AssociatedLocation asloc2 : newList){
                System.debug('On Update==>');
                List<Account_Associated_Location__c> acclocList = [select Id from Account_Associated_Location__c where Associated_Location__c =:asloc2.Id];  //new Account_Associated_Location__c();
                  if(acclocList.size()==0)
                    {
                    OnCreateAccAssociatedLoc(newlist);
                    }
                if(acclocList.size()>0){
                    for(Account_Associated_Location__c accloc : acclocList){
                        accloc.ActiveTo__c = asloc2.ActiveTo;
                        accloc.Active_From__c = asloc2.ActiveFrom;
                        accloc.ParentRecordId__c = asloc2.ParentRecordId;
                        accloc.Payment_Status__c = asloc2.Payment_Status__c;
                        accloc.Status__c = asloc2.Status__c;
                        accloc.Type__c =asloc2.Type;
                        accloc.LocationId__c = asloc2.LocationId;
                        accloc.Name = asloc2.AssociatedLocationNumber;
                        associatedlocToUpdate.add(accloc); 
                    }
                                       
                }
                
            }
            if(!associatedlocToUpdate.isEmpty()){
                update associatedlocToUpdate;
            }
        }
        
    }
    //End of onUpdateAccAssociatedLoc method
    
    
    Public static void onDeleteAccAssociatedLoc(List<AssociatedLocation> oldList){
        List<Account_Associated_Location__c> associatedlocToDelete = new List<Account_Associated_Location__c>();  
        system.debug('In delete method onDeleteAccAssociatedLoc=');
        
        For(AssociatedLocation asloc1 : oldList){
            system.debug('asloc1.Id=='+asloc1.Id);
            List<Account_Associated_Location__c> asslocoldList =[Select id from Account_Associated_Location__c where Associated_Location__c =: asloc1.id];
            if(asslocoldList.size()>0){
            for(Account_Associated_Location__c ac : asslocoldList){
                associatedlocToDelete.add(ac); 
                system.debug('In for loop of delete method onDeleteAccAssociatedLoc='+ac);
            }
        }
        }
        if(associatedlocToDelete.size() > 0){
            Delete associatedlocToDelete;  
            system.debug('Afte delete method onDeleteAccAssociatedLoc=');
        }
    } 
    // End Of onDeleteAccAssociatedLoc method
    
}