objects/AssociatedLocation.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>$CustomMetadata.License_Price__mdt.Location_New.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <description>Agent full name</description>
        <formula>FirstName  &amp; &quot; &quot; &amp;  MiddleName &amp; &quot; &quot; &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agent</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>$CustomMetadata.License_Price__mdt.Agent_New.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Statu__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Location.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Payment_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Requests</relationshipLabel>
        <relationshipName>Payment_Requests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RefId__c</fullName>
        <label>RefId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Request #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Response__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmation_Number__c</fullName>
        <label>Confirmation Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payment Responses</relationshipLabel>
        <relationshipName>Payment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReceiveDate__c</fullName>
        <label>ReceiveDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Settlement_Submission_Date__c</fullName>
        <label>Settlement Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Paid_Amount__c</fullName>
        <label>Total Paid Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ePay_Result_Message__c</fullName>
        <label>ePay Result Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ePay_Return_Code__c</fullName>
        <label>ePay Return Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Response</label>
    <nameField>
        <displayFormat>PGR-{000000}</displayFormat>
        <label>Response #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PaymentRequestItems__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Request Items</relationshipLabel>
        <relationshipName>Payment_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Request Items</relationshipLabel>
        <relationshipName>Payment_Request_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ItemType__c</fullName>
        <label>ItemType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Registration</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Add Location</fullName>
                </value>
                <value>
                    <fullName>Add Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Request__c</fullName>
        <label>Payment Request</label>
        <referenceTo>Payment_Request__c</referenceTo>
        <relationshipLabel>Payment Request Items</relationshipLabel>
        <relationshipName>PaymentRequestItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Request Item</label>
    <nameField>
        <displayFormat>PRI - {000000}</displayFormat>
        <label>RequestItems #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PaymentGatewayQCListController.cls
public class PaymentGatewayQCListController {

    @AuraEnabled
    public static List<Contact> getRelatedContact(Id recordId)
    {
        List<Contact> Conlist = [Select id, name,Role__c,Payment_Statu__c,Amount__c from Contact where AccountId =: recordId];
        return Conlist;
    }
    
    @AuraEnabled
    public static Decimal getTotalAmountContact(Id recordId)
    {
        Decimal countamount=0;
        List<Contact> Conlist = [Select id, name,Role__c,Payment_Statu__c,Amount__c from Contact where AccountId =: recordId];
        for(Contact objCont : Conlist){
            countamount = countamount+objCont.Amount__c;
        }
        return countamount;
    }
    
    @AuraEnabled
    public static List<wrapper> getRelatedLocation(Id recordId)
    {
        List<wrapper> lstWrapper = new List<wrapper>();
        List<AssociatedLocation> associatedloclist = [Select Location.Name,Location.LocationType,Amount__c,Payment_Status__c from AssociatedLocation where ParentRecordId =: recordId];
        System.debug(associatedloclist);
        for(AssociatedLocation al : associatedloclist){
          wrapper wc = new wrapper();
          wc.locationName = al.Location.Name;
          wc.locationType =al.Location.LocationType;
          wc.amount = al.Amount__c;
          wc.paymentStatus = al.Payment_Status__c;
          lstWrapper.add(wc);
        }
        
        return lstWrapper;
    }
    
     @AuraEnabled
    public static Decimal getAmountLocation(Id recordId)
    {
        Decimal countamount=0;
        List<AssociatedLocation> associatedloclist = [Select Location.Name,Location.LocationType,Amount__c,Payment_Status__c from AssociatedLocation where ParentRecordId =: recordId];
        for(AssociatedLocation al : associatedloclist){
          countamount = countamount+al.Amount__c;
        }
        
        return countamount;
    }
    
    @AuraEnabled
    public static void insertPaymentRequest(Id recordId)//List<Payment_Request__c> lstPaymentRequest
    {

        List<Payment_Request__c> Conlist = [Select id from Payment_Request__c ];
        for(Payment_Request__c objCont : Conlist){
           // countamount = countamount+objCont.Amount__c; where Account__c =: lstPaymentReques
        }
        
        Payment_Request__c paymentReq =  new Payment_Request__c();
        //paymentReq.UserId__c = 'TestUserId';
        paymentReq.StartDate__c = System.Today();
        paymentReq.EndDate__c = System.Today();
        paymentReq.RefId__c = '123';
        paymentReq.Status__c = 'Pending';
        paymentReq.Account__c = recordId;
        //paymentReq.Amount__c=100;
        Insert paymentReq;
        
        
        PaymentRequestItems__c paymentReqItems = new PaymentRequestItems__c();
        paymentReqItems.ItemType__c='Add Agent';
        paymentReqItems.Amount__c = 50;
        paymentReqItems.Status__c = 'Pending';
        paymentReqItems.Payment_Request__c = paymentReq.id;
        //paymentReqItems.Agent__c = recordId;
        insert paymentReqItems;
        
        Payment_Response__c paymentResponse = new Payment_Response__c();
        paymentResponse.ReceiveDate__c = System.today();
        paymentResponse.ePay_Return_Code__c = 'Valic Code';
        paymentResponse.Total_Paid_Amount__c = 600;
        paymentResponse.Card_Type__c = 'Visa';
        paymentResponse.Payment_Request__c = paymentReq.id;
        paymentResponse.Status__c = 'Pending';
        paymentResponse.ePay_Result_Message__c = 'Success';
        paymentResponse.Confirmation_Number__c = 200;
        paymentResponse.Settlement_Submission_Date__c = System.today();
        insert paymentResponse;

    }
    
     @AuraEnabled
    public static void insertRequestItem(List<Payment_Response__c> lstPaymentResponses)
    {

        List<Payment_Response__c> Conlist = [Select id from Payment_Response__c ];
        for(Payment_Response__c objCont : Conlist){
		//where AccountId =: lstPaymentResponses
        }

    }
       
	public class wrapper{
        @AuraEnabled public String locationName;
        @AuraEnabled public String locationType;
        @AuraEnabled public Decimal amount;
        @AuraEnabled public String paymentStatus;
    }  
}