objects/Contact.object
<CustomObject>
    <fields>
        <fullName>License_From_Date__c</fullName>
        <label>License From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_No__c</fullName>
        <label>License No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_To_Date__c</fullName>
        <label>License To Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AgentPDFCtrl.cls
public with sharing class AgentPDFCtrl {
    public Contact conRec{get;set;}
    public String dateStr{get;set;}
    public AgentPDFCtrl() {
       // String recId =  apexpages.currentpage().getparameters().get('id');
        User userRec = [select Id,ContactId  from User where Id =: UserInfo.getUserId()];
        conRec = [Select Id,Name,License_From_Date__c,License_To_Date__c,License_No__c from Contact where Id =: userRec.ContactId ];
        if(conRec.License_To_Date__c !=null){
            Datetime dt = conRec.License_To_Date__c; 
            dateStr = dt.format('MM/dd/yyyy');
        }
        
    }
}